int curi=0;
char commandcnt[100][1024];
int pidsave[100];
char maincommand[1024];
int curfg=0;
char lastdir[1024];
int changeflag=0;
int cdflag=0;
#include "tokenise.c"
#include "execute.c"
#include "cdCommand.c"
#include "lsCommand.c"
#include "piping.c"
#include "trimSpace.c"
#include "pinfo.c"
#include "redirection.c"
#include "envar.c"
#include "history.c"
#include "sysCommands.c"
#include "jobs.c"
#include "kjob.c"
#include "fg.c"
#include "bg.c"
#include "signals.c"
